# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='\u540d\u79f0')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='area.Area', verbose_name='\u4e0a\u7ea7\u533a\u57df')),
            ],
            options={
                'db_table': 'area',
                'verbose_name': '\u7701/\u5e02/\u5730\u533a(\u53bf)',
                'verbose_name_plural': '\u7701/\u5e02/\u5730\u533a(\u53bf)',
            },
        ),
    ]
