version: "3"
services:
  web:
    image: test_scripts:latest
    environment:
      - POSTGRESQL_DATABASE=test_scripts
      - POSTGRESQL_USER=test_scripts
      - POSTGRESQL_PASSWORD=test_scripts
      - POSTGRESQL_HOST=db
      - POSTGRESQL_PORT=5432
    expose:
      - 8000
    links:
      - db:db
    depends_on:
      - db
    volumes:
      - ../../src:/code
    command: ./run-unittest.sh

  db:
    image: postgres:9.3
    expose:
      - 5432
    environment:
     - POSTGRES_DB=test_scripts
     - POSTGRES_USER=test_scripts
     - POSTGRES_PASSWORD=test_scripts
